import { InstanceBase, InstanceStatus, runEntrypoint } from '@companion-module/base'
import WebSocket from 'ws'
import { randomBytes } from 'node:crypto'

const MODULE_VERSION = '0.11.1'
const PROTOCOL_VERSION = 1
const DEFAULT_HOST = '127.0.0.1'
const DEFAULT_PORT = 8170
const RECONNECT_MS = 2000
const DEFAULT_HEARTBEAT_MS = 30000
const HEARTBEAT_GRACE_MS = 5000
const GRACEFUL_DISCONNECT_FLUSH_MS = 150
const STATUS_BAR_TEXT_MAX = 1024
const DEFAULT_MAX_STATUS_BAR_ZONES = 6
const MIN_MAX_STATUS_BAR_ZONES = 1
const MAX_MAX_STATUS_BAR_ZONES = 10
const DEFAULT_MARKER_ARG_VARIABLES = 1
const MIN_MARKER_ARG_VARIABLES = 0
const MAX_MARKER_ARG_VARIABLES = 5
const MIN_FONT_SIZE_PX = 20
const MAX_FONT_SIZE_PX = 100
const MIN_RECORDING_DOCK_OPACITY = 30
const MAX_RECORDING_DOCK_OPACITY = 100
const STATUS_BAR_MODES = new Set(['off', 'top', 'bottom'])
const STATUS_BAR_ALIGNS = new Set(['left', 'center', 'right'])
const SERVER_DISCONNECT_REASONS = new Set(['shutdown', 'restart', 'exit'])
const DIAGNOSTIC_ICONS = { green:'🟢', yellow:'🟡', red:'🔴', gray:'⚪' }
const NAV_METHODS = { GO_START:['goStart',false], MARKER_BACK:['markerBack',true], GO_BACK:['goBack',true], GO_CURRENT:['goCurrent',true], GO_NEXT:['goNext',true], MARKER_NEXT:['markerNext',true], GO_FINISH:['goFinish',false] }

function uuidV7(){const b=randomBytes(16),ms=BigInt(Date.now());b[0]=Number((ms>>40n)&255n);b[1]=Number((ms>>32n)&255n);b[2]=Number((ms>>24n)&255n);b[3]=Number((ms>>16n)&255n);b[4]=Number((ms>>8n)&255n);b[5]=Number(ms&255n);b[6]=(b[6]&15)|112;b[8]=(b[8]&63)|128;const h=b.toString('hex');return`${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`}
function jsonValue(v,fallback=''){if(v===undefined||v===null)return fallback;if(typeof v==='string')return v;try{return JSON.stringify(v)}catch{return String(v)}}
function isObject(v){return!!v&&typeof v==='object'&&!Array.isArray(v)}
function hasOnlyKeys(obj,allowed){return Object.keys(obj).every(k=>allowed.includes(k))}
function unicodeLength(v){return Array.from(String(v)).length}
function isGoogleDocUrl(value){try{const u=new URL(String(value));return u.protocol==='https:'&&u.hostname==='docs.google.com'&&u.pathname.startsWith('/document/')}catch{return false}}

class VoicePrompterInstance extends InstanceBase {
 config={};ws=null;reconnectTimer=null;heartbeatTimer=null;heartbeatTimeout=null;pendingPingId=null;destroyed=false;heartbeatIntervalMs=DEFAULT_HEARTBEAT_MS;lastActivityAt=Date.now();peerConnected=false;serverDisconnectReason=null;statusBarMemory={mode:null,activeZoneCount:null,zones:{}};lastMarkerCommand='';lastMarkerArgs=[];lastWord=''
 async init(config){this.config=this.normalizeConfig(config,true);this.statusBarMemory={mode:null,activeZoneCount:this.getMaxZones(),zones:{}};this.destroyed=false;this.defineVariables();this.defineActions();this.definePresets();this.resetVariables();this.publishStatusBarVariables();this.publishMarkerVariables();this.setHealth('gray','Initializing VoicePrompter connection',InstanceStatus.Connecting);this.connect()}
 async destroy(){this.destroyed=true;this.clearReconnect();this.stopHeartbeat();await this.announceDisconnecting('user');this.disconnect()}
 async configUpdated(config){const oldUrl=this.getUrl(),oldMax=this.getMaxZones(),oldMarkerVars=this.getMarkerArgVariableCount();this.config=this.normalizeConfig(config,false);const newUrl=this.getUrl(),newMax=this.getMaxZones(),newMarkerVars=this.getMarkerArgVariableCount();if(newMarkerVars!==oldMarkerVars){this.defineVariables();this.publishMarkerVariables()}if(newMax!==oldMax){this.enforceMaxZoneLimit();this.publishStatusBarVariables();if(this.peerConnected&&this.statusBarMemory.mode&&this.statusBarMemory.mode!=='off')this.replayStatusBarZones()}if(oldUrl!==newUrl){await this.announceDisconnecting('user');this.disconnect();this.connect()}}
 normalizeConfig(config,persist=false){const n={...(config??{})};let changed=false;let host=String(n.host??'').trim(),port=Number(n.port),apiKey=String(n.apiKey??'').trim(),maxZones=Number(n.maxStatusBarZones),markerArgVariables=Number(n.markerArgVariables);if((!host||!Number.isInteger(port)||port<1||port>65535)&&n.url){try{const u=new URL(String(n.url));if(!host&&u.hostname){host=u.hostname;changed=true}if(!Number.isInteger(port)||port<1||port>65535){port=Number(u.port||DEFAULT_PORT);changed=true}}catch{}}if(!host){host=DEFAULT_HOST;changed=true}if(!Number.isInteger(port)||port<1||port>65535){port=DEFAULT_PORT;changed=true}if(!Number.isInteger(maxZones)||maxZones<MIN_MAX_STATUS_BAR_ZONES||maxZones>MAX_MAX_STATUS_BAR_ZONES){maxZones=DEFAULT_MAX_STATUS_BAR_ZONES;changed=true}if(!Number.isInteger(markerArgVariables)||markerArgVariables<MIN_MARKER_ARG_VARIABLES||markerArgVariables>MAX_MARKER_ARG_VARIABLES){markerArgVariables=DEFAULT_MARKER_ARG_VARIABLES;changed=true}if('statusBarSnapshot'in n){delete n.statusBarSnapshot;changed=true}n.host=host;n.port=port;n.apiKey=apiKey;n.maxStatusBarZones=maxZones;n.markerArgVariables=markerArgVariables;if(persist&&changed)this.saveConfig(n);return n}
 getConfigFields(){return[{type:'textinput',id:'host',label:'VPBridge IP Address',width:8,default:DEFAULT_HOST},{type:'number',id:'port',label:'Port',width:4,default:DEFAULT_PORT,min:1,max:65535,step:1,required:true},{type:'textinput',id:'apiKey',label:'API Key',width:12,default:'',tooltip:'Required when VPBridge is set to All Interfaces. Leave empty for Local only.'},{type:'number',id:'maxStatusBarZones',label:'Maximum Status Bar zones',width:6,default:DEFAULT_MAX_STATUS_BAR_ZONES,min:MIN_MAX_STATUS_BAR_ZONES,max:MAX_MAX_STATUS_BAR_ZONES,step:1,required:true,tooltip:'Practical VPM UI limit and the default active zone count after VPM/Companion start. VPP itself has no maximum zone count.'},{type:'number',id:'markerArgVariables',label:'Marker argument variables',width:6,default:DEFAULT_MARKER_ARG_VARIABLES,min:MIN_MARKER_ARG_VARIABLES,max:MAX_MARKER_ARG_VARIABLES,step:1,required:true,tooltip:'Registers marker_arg0 through marker_argN-1 as direct Companion variables. Range 0-5.'},{type:'checkbox',id:'debug',label:'Debug incoming messages',width:6,default:false}]}
 getConnectionSettings(){let host=String(this.config?.host??'').trim()||DEFAULT_HOST,port=Number(this.config?.port);if(!Number.isInteger(port))port=DEFAULT_PORT;return{host,port,apiKey:String(this.config?.apiKey??'').trim()}}
 getUrl(){const{host,port,apiKey}=this.getConnectionSettings();const u=new URL(`ws://${host}:${port}/bc`);if(apiKey)u.searchParams.set('apiKey',apiKey);return u.toString()}
 getDisplayUrl(){const{host,port}=this.getConnectionSettings();return`ws://${host}:${port}/bc`}
 getMaxZones(){const n=Number(this.config?.maxStatusBarZones);return Number.isInteger(n)&&n>=MIN_MAX_STATUS_BAR_ZONES&&n<=MAX_MAX_STATUS_BAR_ZONES?n:DEFAULT_MAX_STATUS_BAR_ZONES}
 getMarkerArgVariableCount(){const n=Number(this.config?.markerArgVariables);return Number.isInteger(n)&&n>=MIN_MARKER_ARG_VARIABLES&&n<=MAX_MARKER_ARG_VARIABLES?n:DEFAULT_MARKER_ARG_VARIABLES}
 sourceInfo(){return{app:'VoicePrompterModule',version:MODULE_VERSION,instance:this.label||this.id}}
 envelope(type,recipient,extra={}){return{protocolVersion:PROTOCOL_VERSION,id:uuidV7(),type,from:'bc',recipient,...extra,source:this.sourceInfo(),timestamp:new Date().toISOString()}}
 sendVpp(msg){if(!this.ws||this.ws.readyState!==WebSocket.OPEN)throw new Error('VPBridge is not connected');this.ws.send(JSON.stringify(msg));if(msg.recipient==='vp')this.setVariableValues({last_sent:new Date().toISOString()});if(this.config?.debug)this.log('debug',`TX VPP ${JSON.stringify(msg)}`)}
 sendToVpIfAvailable(msg){if(!this.ws||this.ws.readyState!==WebSocket.OPEN||!this.peerConnected)return false;this.sendVpp(msg);return true}
 isStatusBarMemoryAvailable(){const m=this.statusBarMemory;if(!STATUS_BAR_MODES.has(m.mode))return false;if(m.mode==='off')return true;return Number.isInteger(m.activeZoneCount)&&m.activeZoneCount>=1}
 enforceMaxZoneLimit(){const max=this.getMaxZones();if(Number.isInteger(this.statusBarMemory.activeZoneCount)&&this.statusBarMemory.activeZoneCount>max)this.statusBarMemory.activeZoneCount=max;return max}
 publishStatusBarVariables(){const m=this.statusBarMemory;this.setVariableValues({status_bar_mode:m.mode??'',status_bar_enabled:m.mode===null?'':(m.mode==='off'?0:1),status_bar_zone_count:m.activeZoneCount??'',status_bar_max_zones:this.getMaxZones(),status_bar_snapshot:JSON.stringify(m)})}
 updateStatusBarMode(mode){this.statusBarMemory.mode=mode;this.publishStatusBarVariables()}
 updateStatusBarCount(count){this.statusBarMemory.activeZoneCount=count;this.publishStatusBarVariables()}
 updateStatusBarZone(index,text,align){this.statusBarMemory.zones[String(index)]={text,align};this.publishStatusBarVariables()}
 clearStatusBarZones(){this.statusBarMemory.zones={};this.publishStatusBarVariables()}
 sendRememberedZone(index){const zone=this.statusBarMemory.zones[String(index)];if(!zone)return false;return this.sendToVpIfAvailable(this.envelope('call','vp',{method:'setStatusBarZone',args:{index,text:zone.text,align:zone.align},expectsResponse:false}))}
 replayStatusBarZones(){if(!this.peerConnected||!this.ws||this.ws.readyState!==WebSocket.OPEN)return false;const mode=this.statusBarMemory.mode,count=this.statusBarMemory.activeZoneCount;if(mode!=='top'&&mode!=='bottom'||!Number.isInteger(count)||count<1)return false;const effectiveCount=Math.min(count,this.getMaxZones());this.sendVpp(this.envelope('call','vp',{method:'setStatusBarZoneCount',args:{count:effectiveCount},expectsResponse:false}));for(let i=1;i<=effectiveCount;i++)this.sendRememberedZone(i);return true}
 replayStatusBarMemory(){if(!this.isStatusBarMemoryAvailable()||!this.peerConnected||!this.ws||this.ws.readyState!==WebSocket.OPEN)return false;const mode=this.statusBarMemory.mode;this.sendVpp(this.envelope('call','vp',{method:'setStatusBarMode',args:{mode},expectsResponse:false}));if(mode==='top'||mode==='bottom')this.replayStatusBarZones();return true}
 getDiagnosticParts(level){let bridge,vp;if(this.serverDisconnectReason)bridge=`${DIAGNOSTIC_ICONS.yellow} ${this.serverDisconnectReason==='restart'?'Restarting':this.serverDisconnectReason==='shutdown'?'Shutting down':'Exiting'}`;else if(this.ws?.readyState===WebSocket.OPEN)bridge=`${DIAGNOSTIC_ICONS.green} Connected`;else if(level==='gray')bridge=`${DIAGNOSTIC_ICONS.gray} Connecting / unknown`;else bridge=`${DIAGNOSTIC_ICONS.red} Disconnected`;if(this.ws?.readyState===WebSocket.OPEN)vp=this.peerConnected?`${DIAGNOSTIC_ICONS.green} Connected`:`${DIAGNOSTIC_ICONS.yellow} Disconnected`;else vp=`${DIAGNOSTIC_ICONS.gray} Unknown`;return{bridge,vp}}
 setHealth(level,reason,statusOverride=null){if(!DIAGNOSTIC_ICONS[level])level='gray';const label=level==='green'?'Connected':level==='yellow'?'Warning':level==='red'?'Error':'Connecting / unknown',parts=this.getDiagnosticParts(level);this.setVariableValues({diagnostic_level:level,diagnostic_status:`${DIAGNOSTIC_ICONS[level]} ${label}`,diagnostic_vpbridge:parts.bridge,diagnostic_voiceprompter:parts.vp,diagnostic_reason:String(reason??'')});const status=statusOverride??(level==='green'?InstanceStatus.Ok:level==='yellow'?(InstanceStatus.UnknownWarning??InstanceStatus.Ok):level==='red'?InstanceStatus.ConnectionFailure:InstanceStatus.Connecting);this.updateStatus(status,String(reason??label))}
 async announceDisconnecting(reason='user'){const s=this.ws;if(!s||s.readyState!==WebSocket.OPEN)return;const msg=this.envelope('event','vp',{event:'disconnecting',args:{reason},expectsResponse:false}),payload=JSON.stringify(msg);this.setVariableValues({last_sent:new Date().toISOString()});if(this.config?.debug)this.log('debug',`TX VPP ${payload}`);await new Promise(resolve=>{let finished=false;const finish=()=>{if(finished)return;finished=true;clearTimeout(timer);resolve()},timer=setTimeout(finish,GRACEFUL_DISCONNECT_FLUSH_MS);try{s.send(payload,finish)}catch{finish()}})}
 defineVariables(){const defs=[{variableId:'connected',name:'VPBridge connected (1/0)'},{variableId:'vp_connected',name:'VoicePrompter mailbox connected (1/0)'},{variableId:'connection_state',name:'Connection state'},{variableId:'diagnostic_level',name:'Diagnostic level (green/yellow/red/gray)'},{variableId:'diagnostic_status',name:'Diagnostic overall status'},{variableId:'diagnostic_vpbridge',name:'Diagnostic VPBridge status'},{variableId:'diagnostic_voiceprompter',name:'Diagnostic VoicePrompter status'},{variableId:'diagnostic_reason',name:'Diagnostic reason'},{variableId:'word',name:'Current VoicePrompter word'},{variableId:'status_bar_mode',name:'Status Bar remembered mode (off/top/bottom)'},{variableId:'status_bar_enabled',name:'Status Bar remembered enabled state (1/0)'},{variableId:'status_bar_zone_count',name:'Status Bar remembered active zone count'},{variableId:'status_bar_max_zones',name:'Status Bar configured maximum zones'},{variableId:'status_bar_snapshot',name:'Status Bar runtime memory JSON'},{variableId:'heartbeat_interval_ms',name:'Heartbeat interval ms'},{variableId:'protocol_version',name:'Protocol version'},{variableId:'id',name:'Message ID'},{variableId:'correlation_id',name:'Correlation ID'},{variableId:'type',name:'Message type'},{variableId:'from',name:'From mailbox'},{variableId:'recipient',name:'Recipient mailbox'},{variableId:'method',name:'Call method'},{variableId:'event',name:'Event name'},{variableId:'command',name:'Marker command'},{variableId:'marker_args',name:'Marker arguments JSON'},{variableId:'arg_offset',name:'Call args.offset'},{variableId:'data',name:'Data JSON'},{variableId:'result',name:'Result JSON'},{variableId:'error_code',name:'Error code'},{variableId:'error_message',name:'Error message'},{variableId:'error_details',name:'Error details JSON'},{variableId:'source_app',name:'Source application'},{variableId:'source_version',name:'Source application version'},{variableId:'source_instance',name:'Source instance'},{variableId:'timestamp',name:'Protocol timestamp'},{variableId:'payload',name:'Complete JSON payload'},{variableId:'last_received',name:'Local receive timestamp'},{variableId:'last_sent',name:'Local send timestamp'},{variableId:'protocol_error',name:'Last VPP validation error'}];for(let i=0;i<this.getMarkerArgVariableCount();i++)defs.push({variableId:`marker_arg${i}`,name:`Marker argument ${i}`});this.setVariableDefinitions(defs)}
 resetVariables(){const values={connected:0,vp_connected:0,connection_state:'disconnected',diagnostic_level:'gray',diagnostic_status:'⚪ Connecting / unknown',diagnostic_vpbridge:'⚪ Connecting / unknown',diagnostic_voiceprompter:'⚪ Unknown',diagnostic_reason:'Initializing',word:this.lastWord,status_bar_mode:'',status_bar_enabled:'',status_bar_zone_count:this.statusBarMemory.activeZoneCount??'',status_bar_max_zones:this.getMaxZones(),status_bar_snapshot:JSON.stringify(this.statusBarMemory),heartbeat_interval_ms:DEFAULT_HEARTBEAT_MS,protocol_version:'',id:'',correlation_id:'',type:'',from:'',recipient:'',method:'',event:'',command:'',marker_args:'',arg_offset:'',data:'',result:'',error_code:'',error_message:'',error_details:'',source_app:'',source_version:'',source_instance:'',timestamp:'',payload:'',last_received:'',last_sent:'',protocol_error:''};for(let i=0;i<this.getMarkerArgVariableCount();i++)values[`marker_arg${i}`]='';this.setVariableValues(values)}
 publishMarkerVariables(){const values={command:this.lastMarkerCommand,marker_args:JSON.stringify(this.lastMarkerArgs)};for(let i=0;i<this.getMarkerArgVariableCount();i++)values[`marker_arg${i}`]=this.lastMarkerArgs[i]===undefined?'':jsonValue(this.lastMarkerArgs[i]);this.setVariableValues(values)}
 validateZoneText(text){text=String(text);if(unicodeLength(text)>STATUS_BAR_TEXT_MAX)throw new Error(`Status Bar zone text exceeds ${STATUS_BAR_TEXT_MAX} characters`);return text}
 async resolvePositiveInteger(raw){const resolved=await this.parseVariablesInString(String(raw??'')),n=Number(String(resolved).trim());return Number.isInteger(n)&&n>=1?n:null}
 defineActions(){const navChoices=[{id:'GO_START',label:'Go Start'},{id:'MARKER_BACK',label:'Marker Back'},{id:'GO_BACK',label:'Go Back'},{id:'GO_CURRENT',label:'Go Current'},{id:'GO_NEXT',label:'Go Next'},{id:'MARKER_NEXT',label:'Marker Next'},{id:'GO_FINISH',label:'Go Finish'}],modeChoices=[{id:'off',label:'Off'},{id:'top',label:'Top'},{id:'bottom',label:'Bottom'}],alignChoices=[{id:'left',label:'Left'},{id:'center',label:'Center'},{id:'right',label:'Right'}],onOffToggleChoices=[{id:'on',label:'On'},{id:'off',label:'Off'},{id:'toggle',label:'Toggle'}];this.setActionDefinitions({
  navigation:{name:'Navigation: Control',options:[{type:'dropdown',id:'instruction',label:'Instruction',choices:navChoices,default:'GO_NEXT'},{type:'textinput',id:'offset',label:'Offset',default:'1',useVariables:true,multiline:true,isVisible:o=>NAV_METHODS[String(o.instruction??'GO_NEXT')]?.[1]===true}],callback:async action=>{const entry=NAV_METHODS[String(action.options.instruction??'GO_NEXT')];if(!entry)throw new Error('Unsupported Navigation instruction');const[method,usesOffset]=entry,args={};if(usesOffset){const raw=await this.parseVariablesInString(String(action.options.offset??'')),offset=Number(String(raw).trim());if(!Number.isInteger(offset))throw new Error('Navigation offset must resolve to an integer');args.offset=offset}this.sendVpp(this.envelope('call','vp',{method,args,expectsResponse:true}))}},
  microphone:{name:'Audio: Microphone',options:[{type:'dropdown',id:'state',label:'State',choices:onOffToggleChoices,default:'toggle'}],callback:async action=>{const state=String(action.options.state??'toggle');if(!['on','off','toggle'].includes(state))throw new Error('Invalid microphone state');this.sendVpp(this.envelope('call','vp',{method:'setMicrophone',args:{state},expectsResponse:true}))}},
  font_size:{name:'Reading: Font Size',options:[{type:'textinput',id:'size',label:'Font size (px)',default:'50',useVariables:true,multiline:false,tooltip:`Must resolve to a whole number from ${MIN_FONT_SIZE_PX} to ${MAX_FONT_SIZE_PX} px.`}],callback:async action=>{const raw=await this.parseVariablesInString(String(action.options.size??'')),size=Number(String(raw).trim());if(!Number.isInteger(size)||size<MIN_FONT_SIZE_PX||size>MAX_FONT_SIZE_PX)return;this.sendVpp(this.envelope('call','vp',{method:'setFontSize',args:{size},expectsResponse:true}))}},
  font_size_adjust:{name:'Reading: Font Size Adjust',options:[{type:'textinput',id:'delta',label:'Adjustment (px)',default:'0',useVariables:true,multiline:false,tooltip:`Relative whole-number change to the current font size. Examples: +5, -5, 0. VoicePrompter clamps the final font size to the same absolute ${MIN_FONT_SIZE_PX}–${MAX_FONT_SIZE_PX} px range used by Font Size.`}],callback:async action=>{const raw=await this.parseVariablesInString(String(action.options.delta??'')),delta=Number(String(raw).trim());if(!Number.isInteger(delta))return;this.sendVpp(this.envelope('call','vp',{method:'adjustFontSize',args:{delta},expectsResponse:true}))}},
  alignment:{name:'Reading: Text Alignment',options:[{type:'dropdown',id:'align',label:'Text Alignment',choices:alignChoices,default:'left'}],callback:async action=>{const align=String(action.options.align??'left');if(!['left','center','right'].includes(align))throw new Error('Invalid text alignment');this.sendVpp(this.envelope('call','vp',{method:'setAlignment',args:{align},expectsResponse:true}))}},
  mirror_mode:{name:'Display: Mirror Mode',options:[{type:'dropdown',id:'state',label:'State',choices:onOffToggleChoices,default:'toggle'}],callback:async action=>{const state=String(action.options.state??'toggle');if(!['on','off','toggle'].includes(state))throw new Error('Invalid Mirror Mode state');this.sendVpp(this.envelope('call','vp',{method:'setMirrorMode',args:{state},expectsResponse:true}))}},
  recording_dock_opacity:{name:'Display: Recording Dock Opacity',options:[{type:'textinput',id:'opacity',label:'Opacity (%)',default:'65',useVariables:true,multiline:false,tooltip:`Must resolve to a whole number from ${MIN_RECORDING_DOCK_OPACITY} to ${MAX_RECORDING_DOCK_OPACITY}.`}],callback:async action=>{const raw=await this.parseVariablesInString(String(action.options.opacity??'')),opacity=Number(String(raw).trim());if(!Number.isInteger(opacity)||opacity<MIN_RECORDING_DOCK_OPACITY||opacity>MAX_RECORDING_DOCK_OPACITY)return;this.sendVpp(this.envelope('call','vp',{method:'setRecordingDockOpacity',args:{opacity},expectsResponse:true}))}},
  recording_dock_opacity_adjust:{name:'Display: Recording Dock Opacity Adjust',options:[{type:'textinput',id:'delta',label:'Adjustment (%)',default:'0',useVariables:true,multiline:false,tooltip:`Relative whole-number change to the current Recording Dock opacity. Examples: +5, -5, 0. VoicePrompter clamps the final opacity to the same absolute ${MIN_RECORDING_DOCK_OPACITY}–${MAX_RECORDING_DOCK_OPACITY}% range used by Recording Dock Opacity.`}],callback:async action=>{const raw=await this.parseVariablesInString(String(action.options.delta??'')),delta=Number(String(raw).trim());if(!Number.isInteger(delta))return;this.sendVpp(this.envelope('call','vp',{method:'adjustRecordingDockOpacity',args:{delta},expectsResponse:true}))}},
  voice_commands:{name:'Audio: Voice Commands',options:[{type:'dropdown',id:'state',label:'State',choices:onOffToggleChoices,default:'toggle'}],callback:async action=>{const state=String(action.options.state??'toggle');if(!['on','off','toggle'].includes(state))throw new Error('Invalid Voice Commands state');this.sendVpp(this.envelope('call','vp',{method:'setVoiceCommands',args:{state},expectsResponse:true}))}},
  rotate_screen:{name:'Display: Rotate Screen',options:[{type:'dropdown',id:'state',label:'State',choices:onOffToggleChoices,default:'toggle'}],callback:async action=>{const state=String(action.options.state??'toggle');if(!['on','off','toggle'].includes(state))throw new Error('Invalid Rotate Screen state');this.sendVpp(this.envelope('call','vp',{method:'setRotateScreen',args:{state},expectsResponse:true}))}},
  sync_google_doc:{name:'Document: Synchronize Google Doc',options:[],callback:async()=>{this.sendVpp(this.envelope('call','vp',{method:'syncGoogleDoc',args:{},expectsResponse:true}))}},
  set_google_doc_url:{name:'Document: Set Google Doc URL',options:[{type:'textinput',id:'url',label:'Google Doc URL',default:'',useVariables:true,multiline:false,tooltip:'HTTPS Google Docs document URL. Companion variables/expressions are supported.'}],callback:async action=>{const url=String(await this.parseVariablesInString(String(action.options.url??''))).trim();if(!isGoogleDocUrl(url))throw new Error('Google Doc URL must be an HTTPS docs.google.com/document/... URL');this.sendVpp(this.envelope('call','vp',{method:'setGoogleDocUrl',args:{url},expectsResponse:true}))}},
  status_bar_mode:{name:'Status Bar: Mode',options:[{type:'dropdown',id:'mode',label:'Mode',choices:modeChoices,default:'bottom'}],callback:async action=>{const mode=String(action.options.mode??'');if(!STATUS_BAR_MODES.has(mode))throw new Error('Invalid Status Bar mode');this.updateStatusBarMode(mode);this.sendToVpIfAvailable(this.envelope('call','vp',{method:'setStatusBarMode',args:{mode},expectsResponse:false}))}},
  status_bar_zone_count:{name:'Status Bar: Set Zone Count',options:[{type:'textinput',id:'count',label:'Number of active zones',default:'2',useVariables:true,multiline:false,tooltip:'Must resolve to an integer from 1 through the configured Maximum Status Bar zones.'}],callback:async action=>{const count=await this.resolvePositiveInteger(action.options.count),max=this.getMaxZones();if(count===null||count>max)return;const previous=Number.isInteger(this.statusBarMemory.activeZoneCount)?this.statusBarMemory.activeZoneCount:0;this.updateStatusBarCount(count);if(this.sendToVpIfAvailable(this.envelope('call','vp',{method:'setStatusBarZoneCount',args:{count},expectsResponse:false}))&&count>previous)for(let i=Math.max(previous+1,1);i<=count;i++)this.sendRememberedZone(i)}},
  status_bar_zone:{name:'Status Bar: Set Zone',options:[{type:'textinput',id:'index',label:'Zone number',default:'1',useVariables:true,multiline:false,tooltip:'Must resolve to an integer from 1 through the configured Maximum Status Bar zones.'},{type:'textinput',id:'text',label:'Content',default:'',useVariables:true,multiline:false},{type:'dropdown',id:'align',label:'Alignment',choices:alignChoices,default:'left'}],callback:async action=>{const index=await this.resolvePositiveInteger(action.options.index),max=this.getMaxZones();if(index===null||index>max)return;const text=this.validateZoneText(await this.parseVariablesInString(String(action.options.text??''))),align=String(action.options.align??'left');if(!STATUS_BAR_ALIGNS.has(align))throw new Error('Invalid Status Bar zone alignment');this.updateStatusBarZone(index,text,align);this.sendRememberedZone(index)}},
  clear_status_bar:{name:'Status Bar: Clear',options:[],callback:async()=>{this.clearStatusBarZones();this.sendToVpIfAvailable(this.envelope('call','vp',{method:'clearStatusBar',args:{},expectsResponse:false}))}},
  json:{name:'Advanced: JSON',description:'Temporary raw WebSocket test action.',options:[{type:'textinput',id:'payload',label:'JSON / Text',default:'',useVariables:true,multiline:true}],callback:async action=>{if(!this.ws||this.ws.readyState!==WebSocket.OPEN)throw new Error('VPBridge is not connected');this.ws.send(await this.parseVariablesInString(String(action.options.payload??'')))}}
 })}
 definePresets(){const p=(name,text,instruction,offset)=>{const options={instruction};if(offset!==undefined)options.offset=String(offset);return{type:'button',category:'Navigation',name,style:{text,size:'18',color:0xffffff,bgcolor:0x000000},steps:[{down:[{actionId:'navigation',options}],up:[]}],feedbacks:[]}};this.setPresetDefinitions({navigation_go_start:p('Go Start','|<\nGo Start','GO_START'),navigation_marker_back:p('Marker Back','[<\nMarker Back','MARKER_BACK',1),navigation_go_back:p('Go Back','<<\nGo Back','GO_BACK',1),navigation_go_current:p('Go Current','<|\nGo Current','GO_CURRENT',1),navigation_go_next:p('Go Next','>>\nGo Next','GO_NEXT',1),navigation_marker_next:p('Marker Next','>]\nMarker Next','MARKER_NEXT',1),navigation_go_finish:p('Go Finish','>|\nGo Finish','GO_FINISH'),connection_diagnostics:{type:'button',category:'Diagnostics',name:'Connection Diagnostics',style:{text:'$(vp:diagnostic_status)\nVPB: $(vp:diagnostic_vpbridge)\nVP: $(vp:diagnostic_voiceprompter)\n$(vp:diagnostic_reason)',size:'12',color:0xffffff,bgcolor:0x000000},steps:[{down:[],up:[]}],feedbacks:[]}})}
 connect(){this.clearReconnect();this.stopHeartbeat();this.serverDisconnectReason=null;const{apiKey}=this.getConnectionSettings(),target=`Connecting to ${this.getDisplayUrl()}`;this.setHealth('gray',target,InstanceStatus.Connecting);if(apiKey&&!/^[a-fA-F0-9]{64}$/.test(apiKey)){this.setHealth('red','API Key must be 64 hexadecimal characters',InstanceStatus.BadConfig);return}try{this.ws=new WebSocket(this.getUrl())}catch(e){this.setHealth('red',e.message,InstanceStatus.ConnectionFailure);this.scheduleReconnect();return}this.ws.on('unexpected-response',(_req,res)=>{const sc=res.statusCode??0;res.resume();const msg=sc===401?'VPBridge authentication failed (401)':`VPBridge rejected connection (${sc})`;this.setDisconnected();this.setHealth('red',msg,InstanceStatus.ConnectionFailure);this.scheduleReconnect()});this.ws.on('open',()=>{this.serverDisconnectReason=null;this.peerConnected=false;this.lastActivityAt=Date.now();this.setVariableValues({connected:1,connection_state:'bridge-only'});this.setHealth('yellow','VPBridge connected; checking VoicePrompter mailbox');this.startHeartbeat();this.sendPing()});this.ws.on('message',d=>this.handleMessage(d));this.ws.on('close',c=>{const gracefulReason=this.serverDisconnectReason;this.setDisconnected();if(gracefulReason)this.setHealth('yellow',`VPBridge ${gracefulReason}; reconnecting`,InstanceStatus.UnknownWarning??InstanceStatus.Disconnected);else this.setHealth('red',`VPBridge disconnected (${c})`,InstanceStatus.Disconnected);this.scheduleReconnect()});this.ws.on('error',e=>{this.setHealth('red',`VPBridge WebSocket error: ${e.message}`,InstanceStatus.ConnectionFailure);this.log('error',`VPBridge WebSocket error: ${e.message}`)})}
 disconnect(){const s=this.ws;this.ws=null;if(s){s.removeAllListeners();try{s.close(1000)}catch{}}this.setDisconnected()}
 setDisconnected(){this.stopHeartbeat();this.peerConnected=false;this.setVariableValues({connected:0,vp_connected:0,connection_state:'disconnected'})}
 scheduleReconnect(){if(this.destroyed||this.reconnectTimer)return;this.reconnectTimer=setTimeout(()=>{this.reconnectTimer=null;if(!this.destroyed)this.connect()},RECONNECT_MS)}
 clearReconnect(){if(this.reconnectTimer){clearTimeout(this.reconnectTimer);this.reconnectTimer=null}}
 startHeartbeat(){this.stopHeartbeat();this.heartbeatTimer=setInterval(()=>this.heartbeatTick(),1000)}
 stopHeartbeat(){if(this.heartbeatTimer){clearInterval(this.heartbeatTimer);this.heartbeatTimer=null}if(this.heartbeatTimeout){clearTimeout(this.heartbeatTimeout);this.heartbeatTimeout=null}this.pendingPingId=null}
 heartbeatTick(){if(!this.ws||this.ws.readyState!==WebSocket.OPEN||this.pendingPingId)return;if(Date.now()-this.lastActivityAt>=this.heartbeatIntervalMs)this.sendPing()}
 sendPing(){if(!this.ws||this.ws.readyState!==WebSocket.OPEN||this.pendingPingId)return;const ping=this.envelope('call','server',{method:'ping',args:{},expectsResponse:true});this.pendingPingId=ping.id;this.lastActivityAt=Date.now();this.sendVpp(ping);this.heartbeatTimeout=setTimeout(()=>{if(this.pendingPingId!==ping.id)return;this.pendingPingId=null;this.setHealth('red','VPBridge heartbeat timeout',InstanceStatus.ConnectionFailure);try{this.ws?.terminate()}catch{}},HEARTBEAT_GRACE_MS)}
 applyPingResponse(m){const result=isObject(m.result)?m.result:{},mailboxes=isObject(result.mailboxes)?result.mailboxes:{},vp=isObject(mailboxes.vp)?mailboxes.vp:{},hb=isObject(result.heartbeat)?result.heartbeat:{};const interval=Number(hb.intervalMs);if(Number.isInteger(interval)&&interval>=5000&&interval<=3600000)this.heartbeatIntervalMs=interval;this.peerConnected=vp.connected===true;this.lastActivityAt=Date.now();this.setVariableValues({vp_connected:this.peerConnected?1:0,heartbeat_interval_ms:this.heartbeatIntervalMs});this.updateConnectionStatus()}
 updateConnectionStatus(){if(!this.ws||this.ws.readyState!==WebSocket.OPEN){this.setVariableValues({connection_state:'disconnected'});return}if(this.peerConnected){this.setVariableValues({connection_state:'connected',vp_connected:1});this.setHealth('green','VPBridge + VoicePrompter connected',InstanceStatus.Ok)}else{this.setVariableValues({connection_state:'bridge-only',vp_connected:0});this.setHealth('yellow','VPBridge connected; VoicePrompter not connected',InstanceStatus.UnknownWarning??InstanceStatus.Ok)}}
 protocolFailure(text,raw=''){this.log('error',`VPP ERROR: ${text}`);this.setVariableValues({protocol_error:text,payload:raw,last_received:new Date().toISOString()})}
 sendAck(m,result={success:true}){this.sendVpp(this.envelope('response',String(m.from),{correlationId:m.id,result}))}
 sendError(m,code,message,details){this.sendVpp(this.envelope('error',String(m.from),{correlationId:m.id,error:{code,message,...(details===undefined?{}:{details})}}))}
 validateEnvelope(m){if(Number(m.protocolVersion)!==PROTOCOL_VERSION)return'Unsupported protocolVersion';if(typeof m.id!=='string'||!m.id)return'Missing message id';if(typeof m.type!=='string')return'Missing message type';if(!['call','event','progress','response','error'].includes(m.type))return`Unknown message type "${m.type}"`;if(!['vp','server'].includes(m.from))return`Invalid from "${m.from}"`;if(m.recipient!=='bc')return'Message recipient must be "bc"';if(!isObject(m.source))return'Missing or invalid source';if(typeof m.timestamp!=='string'||!m.timestamp.trim())return'Missing or invalid timestamp';return null}
 validateTerminalCorrelation(m){if((m.type==='progress'||m.type==='response')&&(typeof m.correlationId!=='string'||!m.correlationId))return`${m.type} is missing correlationId`;if(m.type==='error'&&m.correlationId!==undefined&&typeof m.correlationId!=='string')return'error correlationId must be a string';return null}
 markValidPeerActivity(m){if(m.from!=='vp')return;this.lastActivityAt=Date.now();this.peerConnected=true;this.updateConnectionStatus()}
 handleStatusBarSyncRequest(m){if(m.from!=='vp'||!isObject(m.args)||Object.keys(m.args).length!==0||m.expectsResponse!==true){if(m.expectsResponse===true)this.sendError(m,'INVALID_MESSAGE','Invalid statusBarSyncRequest event');return false}this.markValidPeerActivity(m);const available=this.isStatusBarMemoryAvailable();if(available)this.replayStatusBarMemory();this.sendAck(m,{available});return true}
 handleMessage(rawData){const raw=Buffer.isBuffer(rawData)?rawData.toString('utf8'):String(rawData);let m;try{m=JSON.parse(raw)}catch{this.protocolFailure('Received invalid JSON',raw);return}if(!isObject(m)){this.protocolFailure('JSON root must be an object',raw);return}const envErr=this.validateEnvelope(m);if(envErr){this.protocolFailure(envErr,raw);return}const corrErr=this.validateTerminalCorrelation(m);if(corrErr){this.protocolFailure(corrErr,raw);return}
  if(this.pendingPingId&&m.from==='server'&&m.correlationId===this.pendingPingId&&(m.type==='response'||m.type==='error')){if(this.heartbeatTimeout){clearTimeout(this.heartbeatTimeout);this.heartbeatTimeout=null}this.pendingPingId=null;this.lastActivityAt=Date.now();if(m.type==='response')this.applyPingResponse(m)}
  let argOffset='',eventAckHandled=false,isPeerDisconnecting=false
  if(m.type==='event'){
   if(typeof m.event!=='string'||!m.event){this.protocolFailure('Event name is missing',raw);return}
   if(m.event==='marker'){if(m.from!=='vp'||typeof m.command!=='string'||!m.command.trim()||!Array.isArray(m.args)){if(m.expectsResponse===true)this.sendError(m,'INVALID_MESSAGE','Invalid marker event');this.protocolFailure('Invalid marker event',raw);return}for(const a of m.args)if(!['string','number'].includes(typeof a)||typeof a==='number'&&!Number.isFinite(a)){if(m.expectsResponse===true)this.sendError(m,'INVALID_ARGUMENT','Invalid marker argument');this.protocolFailure('Invalid marker argument',raw);return}this.lastMarkerCommand=m.command;this.lastMarkerArgs=[...m.args];this.publishMarkerVariables()}
   else if(m.event==='wordChanged'){if(m.from!=='vp'||!isObject(m.args)||!hasOnlyKeys(m.args,['word'])||typeof m.args.word!=='string'){if(m.expectsResponse===true)this.sendError(m,'INVALID_MESSAGE','Invalid wordChanged event');this.protocolFailure('Invalid wordChanged event',raw);return}this.lastWord=m.args.word;this.setVariableValues({word:this.lastWord})}
   else if(m.event==='statusBarModeChanged'){if(m.from!=='vp'||!isObject(m.args)||!hasOnlyKeys(m.args,['mode'])||!STATUS_BAR_MODES.has(m.args.mode)){if(m.expectsResponse===true)this.sendError(m,'INVALID_MESSAGE','Invalid statusBarModeChanged event');this.protocolFailure('Invalid statusBarModeChanged event',raw);return}this.markValidPeerActivity(m);this.updateStatusBarMode(m.args.mode);if(m.args.mode!=='off')this.replayStatusBarZones()}
   else if(m.event==='statusBarSyncRequest'){if(!this.handleStatusBarSyncRequest(m)){this.protocolFailure('Invalid statusBarSyncRequest event',raw);return}eventAckHandled=true}
   else if(m.event==='disconnecting'){if(!isObject(m.args)||!hasOnlyKeys(m.args,['reason'])||typeof m.args.reason!=='string'){if(m.expectsResponse===true)this.sendError(m,'INVALID_MESSAGE','Invalid disconnecting event');this.protocolFailure('Invalid disconnecting event',raw);return}const reason=m.args.reason;if(m.from==='vp'){if(reason!=='user'){if(m.expectsResponse===true)this.sendError(m,'INVALID_ARGUMENT','Invalid VP disconnecting reason');this.protocolFailure('Invalid VP disconnecting reason',raw);return}isPeerDisconnecting=true;this.peerConnected=false;this.setVariableValues({vp_connected:0,connection_state:'bridge-only'});this.setHealth('yellow','VoicePrompter announced intentional disconnect',InstanceStatus.UnknownWarning??InstanceStatus.Ok)}else if(m.from==='server'){if(!SERVER_DISCONNECT_REASONS.has(reason)){if(m.expectsResponse===true)this.sendError(m,'INVALID_ARGUMENT','Invalid server disconnecting reason');this.protocolFailure('Invalid server disconnecting reason',raw);return}this.serverDisconnectReason=reason;this.stopHeartbeat();this.peerConnected=false;this.setVariableValues({connected:0,vp_connected:0,connection_state:'disconnected'});this.setHealth('yellow',`VPBridge ${reason}; reconnecting`,InstanceStatus.UnknownWarning??InstanceStatus.Disconnected)}}
   else{if(m.expectsResponse===true)this.sendError(m,'INVALID_MESSAGE',`Unknown event "${m.event}"`);this.protocolFailure(`Unknown event "${m.event}"`,raw);return}
  }
  if(m.type==='call'){if(typeof m.method!=='string'||!isObject(m.args)){if(m.expectsResponse===true)this.sendError(m,'INVALID_MESSAGE','Invalid call');this.protocolFailure('Invalid call',raw);return}if(m.expectsResponse===true)this.sendError(m,'UNKNOWN_METHOD',`VPM has no public method "${m.method}"`)}
  if(m.from==='vp'&&!isPeerDisconnecting)this.markValidPeerActivity(m)
  const source=m.source,error=isObject(m.error)?m.error:{},callArgs=m.type==='call'&&isObject(m.args)?m.args:{};if(callArgs.offset!==undefined)argOffset=jsonValue(callArgs.offset);this.setVariableValues({protocol_version:PROTOCOL_VERSION,id:m.id,correlation_id:m.correlationId??'',type:m.type,from:m.from,recipient:m.recipient,method:m.method??'',event:m.event??'',arg_offset:argOffset,data:jsonValue(m.data),result:jsonValue(m.result),error_code:error.code??'',error_message:error.message??'',error_details:jsonValue(error.details),source_app:source.app??'',source_version:source.version??'',source_instance:source.instance??'',timestamp:m.timestamp,payload:raw,last_received:new Date().toISOString(),protocol_error:''});if(m.type==='event'&&m.expectsResponse===true&&!eventAckHandled)this.sendAck(m);if(this.config?.debug)this.log('debug',`RX VPP ${raw}`)
 }
}
runEntrypoint(VoicePrompterInstance, [])
